//
// DateResult.swift
//
// Generated by swagger-codegen
//

import Foundation



open class DateResult: Codable {

    public var date: String?
    public var green: Bool?

    public init(date: String?, green: Bool?) {
        self.date = date
        self.green = green
    
    }
    
    
    
}

