//
// ScheduleListByDateResult.swift
//
// Generated by swagger-codegen
//

import Foundation



open class ScheduleListByDateResult: Codable {
    
    public var eventsid: String?
    public var eventsdate: String?
    public var eventsdecs: String?
    
    public init(eventsid: String?, eventsdate: String?, eventsdecs: String?) {
        self.eventsid = eventsid
        self.eventsdate = eventsdate
        self.eventsdecs = eventsdecs
    }

}

